name: ESCU Default Configuration TTP
id: 48d6938c-c215-41b2-b325-2a0d43e9ac2f
date: '2026-07-29'
author: jesse12-21
version: 1
status: production
description: Default scheduling and alert action configuration for TTP detections.
type: TTP
scheduling:
  cron_schedule: 0 * * * *
  earliest_time: -70m@m
  latest_time: -10m@m
  schedule_window: auto
alert_action:
  rba:
    enabled: true
